### ISSUE TITLE
activiti启动失败

### ISSUE THREAD

**Issue by codingwk** [fengli01/bpmn-spring-boot#2]
activiti启动失败

RMI TCP Connection(2)-127.0.0.1] INFO  o.a.c.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'

**Comment by fengli01** [comment]
根据你提供的日志，应该是已经启动成功了，如果还存在问题，麻烦email：fengliii123@126.com
